version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: multimodal_rag:latest
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data 